// Central lookup of every HUD element main.js and the ui/ modules wire up.
export const dom = {
  canvas: document.getElementById("scene"),
  fileInput: document.getElementById("fileInput"),
  fileName: document.getElementById("fileName"),
  playPauseBtn: document.getElementById("playPauseBtn"),
  cameraAngleBtnDefault: document.getElementById("cameraAngleBtnDefault"),
  cameraAngleBtnTop: document.getElementById("cameraAngleBtnTop"),
  cameraAngleBtnSide: document.getElementById("cameraAngleBtnSide"),
  cameraAngleBtnFront: document.getElementById("cameraAngleBtnFront"),
  cameraAngleBtnBack: document.getElementById("cameraAngleBtnBack"),
  cameraAngleBtnInside: document.getElementById("cameraAngleBtnInside"),
  loadingEl: document.getElementById("loading"),
  loadingLabel: document.getElementById("loadingLabel"),
  progressFill: document.getElementById("progressFill"),
  controlsEl: document.getElementById("controls"),
  scrubSlider: document.getElementById("scrubSlider"),
  scrubReadout: document.getElementById("scrubReadout"),
  opacitySlider: document.getElementById("opacitySlider"),
  opacityReadout: document.getElementById("opacityReadout"),
  ghostCountSlider: document.getElementById("ghostCountSlider"),
  ghostCountReadout: document.getElementById("ghostCountReadout"),
  motionSlider: document.getElementById("motionSlider"),
  motionReadout: document.getElementById("motionReadout"),
  shellCheckbox: document.getElementById("shellCheckbox"),
  shellOpacitySlider: document.getElementById("shellOpacitySlider"),
  shellOpacityReadout: document.getElementById("shellOpacityReadout"),
  devTools: document.getElementById("devTools"),
  devTestFileSelect: document.getElementById("devTestFileSelect"),
};
